{{- if .Values.frontend.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "frontend.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: {{ .Values.frontend.service.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    buildNumber: "{{ .Values.build.tag }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.frontend.ingress.hostname }}.
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: {{ .Values.frontend.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "frontend.fullname" . }}
              servicePort: {{ .Values.frontend.service.externalPort }}
  {{- if .Values.frontend.ingress.tls.enabled }}
  tls:
    - secretName: {{ template "name" . }}-tls
      hosts:
        - {{ .Values.frontend.ingress.hostname }}
  {{- end -}}
{{- end -}}
